Refactor Dockerfile/main.go location and swtich to a single go.mod file
rturner3/spire-mysql-demo pull request #10
Opened 2023-10-26 18:06 UTC by chiragk25

2023-10-26 18:34 UTC, chiragk25 commented
This change -

- Moves all main.go files under `cmd/`
- Moves all Dockerfiles under root directory
- Moves all Kubernetes config files under `config/k8s/`
- Moves all scripts under `scripts/`

2023-10-27 03:58 UTC, rturner3 approved these changes

2023-10-27 03:58 UTC, rturner3 commented on Dockerfile.tlsreload
> +RUN go build -o /tls-bootstrap ./cmd/mysql/tls-reload
```suggestion
RUN go build -o /tls-reload ./cmd/mysql/tls-reload
```

2023-10-27 03:59 UTC, rturner3 requested changes
Oops, didn't mean to approve. Noticed one bug in one of the Dockerfiles.

2023-10-27 19:29 UTC, chiragk25 commented
Verified `./scripts/push-mysql-tls-images.sh` is able to push both `tls-reload` and `tls-bootstrap` images

2023-10-27 21:02 UTC, rturner3 approved these changes

2023-10-27 21:55 UTC, merged